In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv(r'C:\Users\PC\Desktop\محرومیت\data\labour_force_all_3.csv',low_memory=False)

In [3]:
df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head()

Empty DataFrame
Columns: [Unnamed: 0, pkey, NobatAmargiri, F2_D03, F2_D04, F2_D05, F2_D06, F2_D07, F2_D15, F2_D16, F2_D17, F2_D18, F2_D19, F3_D01, F3_D02, F3_D03, F3_D04, F3_D05, F3_D06, F3_D07, F3_D09, F3_D11, F3_D13, F3_D24, F3_D31, F3_D33, F3_D37MAH, F3_D38, F3_D47, F3_D49, IW_Yearly, ActivityStatus, year, household_number, cluster_number, urban_rural, province_code, sample_year, education_group, dep_sex, dep_urban_rural, dep_edu, dep_age_group, deprived]
Index: []

[0 rows x 44 columns]

In [14]:
df.drop_duplicates()

,Unnamed: 0,pkey,NobatAmargiri,F2_D03,F2_D04,F2_D05,F2_D06,F2_D07,F2_D15,F2_D16,...,cluster_number,urban_rural,province_code,sample_year,education_group,dep_sex,dep_urban_rural,dep_edu,dep_age_group,deprived
0,0,125103261,3,1,1,03,47.0,54.0,2,1,...,32,1,25,1,Health and Welfare,0,0,0,3,0
1,1,125103261,3,2,2,03,58.0,43.0,2,1,...,32,1,25,1,Health and Welfare,1,0,0,3,0
2,2,125103261,3,3,2,03,80.0,21.0,1,1,...,32,1,25,1,Services,1,0,0,1,0
3,3,125103261,3,3,1,08,85.0,16.0,1,1,...,32,1,25,1,Natural Sciences,0,0,1,1,0
4,4,125103262,2,1,1,09,71.0,29.0,2,1,...,32,1,25,1,Engineering and Manufacturing,0,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1509228,1678964,330112680,3,1,1,04,58.0,45.0,2,1,...,126,1,30,3,Arts and Humanities,0,0,0,3,0
1509229,1678965,330112680,3,2,2,09,56.0,46.0,2,1,...,126,1,30,3,Arts and Humanities,1,0,0,3,1
1509230,1678966,330112680,3,3,1,04,83.0,20.0,1,1,...,126,1,30,3,ICT,0,0,0,1,0
1509231,1678968,330112680,4,1,1,04,58.0,45.0,2,1,...,126,1,30,3,Arts and Humanities,0,0,0,3,0
1509232,1678969,330112680,4,2,2,09,56.0,46.0,2,1,...,126,1,30,3,Arts and Humanities,1,0,0,3,1

In [5]:
df['F2_D19'] = pd.to_numeric(df['F2_D19'], errors='coerce')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1509233 entries, 0 to 1509232
Data columns (total 44 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Unnamed: 0        1509233 non-null  int64
 1   pkey              1509233 non-null  int64
 2   NobatAmargiri     1509233 non-null  int64
 3   F2_D03            1509233 non-null  object
 4   F2_D04            1509233 non-null  int64
 5   F2_D05            1320423 non-null  object
 6   F2_D06            1475087 non-null  float64
 7   F2_D07            1509233 non-null  float64
 8   F2_D15            1509233 non-null  int64
 9   F2_D16            1509233 non-null  int64
 10  F2_D17            1270273 non-null  float64
 11  F2_D18            648995 non-null   object
 12  F2_D19            1509168 non-null  float64
 13  F3_D01            1509233 non-null  int64
 14  F3_D02            1019012 non-null  float64
 15  F3_D03            1007248 non-null  float64
 16  F3_D04            978720 non-null   float64
 17  F3_D05            976032 non-null   float64
 18  F3_D06            971710 non-null   float64
 19  F3_D07            17792 non-null    object
 20  F3_D09            555315 non-null   object
 21  F3_D11            555315 non-null   float64
 22  F3_D13            555315 non-null   object
 23  F3_D24            555305 non-null   object
 24  F3_D31            953918 non-null   float64
 25  F3_D33            905407 non-null   float64
 26  F3_D37MAH         27270 non-null    float64
 27  F3_D38            27260 non-null    object
 28  F3_D47            905042 non-null   float64
 29  F3_D49            1509233 non-null  float64
 30  IW_Yearly         1509233 non-null  float64
 31  ActivityStatus    1509233 non-null  int64
 32  year              1509233 non-null  int64
 33  household_number  1509233 non-null  int64
 34  cluster_number    1509233 non-null  int64
 35  urban_rural       1509233 non-null  int64
 36  province_code     1509233 non-null  int64
 37  sample_year       1509233 non-null  int64
 38  education_group   648235 non-null   object
 39  dep_sex           1509233 non-null  int64
 40  dep_urban_rural   1509233 non-null  int64
 41  dep_edu           1509233 non-null  int64
 42  dep_age_group     1509233 non-null  int64
 43  deprived          1509233 non-null  int64
dtypes: float64(16), int64(19), object(9)
memory usage: 506.6+ MB

In [7]:
df_new1 = df.dropna(subset=['F2_D19'])

In [15]:
df_new.to_csv(r'C:\Users\PC\Desktop\محرومیت\data\labour_force_all_3.csv')

In [14]:
df_new = df.drop(columns=['F3_D37MAH','F3_D38','F3_D07'])